blog/blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView


urlpatterns = [
    url(r'^', include("posts.urls", namespace='posts')),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'logged_out.html'}, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#from posts.views import post_home
#url(r'^posts/$', post_home),

blog/posts/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='list'),
    url(r'^create/$', views.post_create, name='create'),
    url(r'^(?P<id>\d+)/$', views.post_detail, name='detail'),
    url(r'^(?P<id>\d+)/edit/$', views.post_update.as_view(), name ='update'),
    url(r'^(?P<id>\d+)/delete/$', views.post_delete, name ='delete'),
    url(r'^new_user/$', views.adduser, name='new_user'),

]

blog/posts/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

from django.core.urlresolvers import reverse
from django.conf import settings
from django.contrib.auth.models import User

class Post(models.Model):
	title = models.CharField(max_length=120)
	content = models.TextField()
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
	image = models.FileField(null=True, blank=True)
	user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
		
	def __unicode__(self):
		return self.title

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("posts:detail", kwargs={"id": self.id})

	class Meta:
		ordering = ["-timestamp", "-updated"]

	def get_absolute_url_edit(self):
		return reverse("posts:update", kwargs={"id": self.id})

	def get_absolute_url_delete(self):
		return reverse("posts:delete", kwargs={"id": self.id})

class Commentary(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, default=2)
	content = models.TextField()
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
	post = models.ForeignKey('Post')

blog/posts/forms.py
from django import forms

from .models import Post, Commentary
from django.contrib.auth.models import User


class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ["title", "content", "image"]

class CommentaryForm(forms.ModelForm):
	class Meta:
		model = Commentary
		fields = ["content"]

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')

blog/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect , Http404
from django.contrib import messages

# Create your views here.
from .models import Post, Commentary
from .forms import PostForm, CommentaryForm, UserForm

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q

from django.contrib.auth import login
from django.contrib.auth.models import User

from django.views import View




def post_create(request):
	if not (request.user.is_staff or request.user.is_superuser):
		raise Http404

	form = PostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
			instance = form.save(commit=False)
			instance.user = request.user
			instance.save()
			messages.success(request, "Successfully created")
			return HttpResponseRedirect(instance.get_absolute_url())
	context = {
		"form": form,
	}
	return render(request, "post_form.html", context)

def post_detail(request, id=None):
	instance = get_object_or_404(Post, id=id)
	try:
		commentary_list = Commentary.objects.filter(post=instance)
	except:
		commentary_list = None
	
	form = CommentaryForm(request.POST or None)
	if form.is_valid():
			instance2 = form.save(commit=False)
			try:
				instance2.user = request.user
			except:
				pass

			instance2.post = instance
			instance2.save()
			messages.success(request, "Successfully created a commentary")
			return HttpResponseRedirect(instance.get_absolute_url())
	context = {
			"title": instance.title,
			"instance": instance,
			"form":form,
			"commentary_list":commentary_list

		}
	return render(request, "post_detail.html", context)

def post_list(request):
	queryset_list = Post.objects.all()

	query = request.GET.get("q")
	if query:
		queryset_list = queryset_list.filter(
			Q(title__icontains=query)|Q(content__icontains=query)
			).distinct()

	paginator = Paginator(queryset_list, 5) # Show 5 contacts per page
	page = request.GET.get('page')
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
	# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)

	context = {
			"object_list": queryset,
			"title": "List"
		}
	return render(request, "post_list.html", context)
	
class post_update(View):
	model = Post
	def get(self, request, id=None):
		if not (request.user.is_staff or request.user.is_superuser):
			raise Http404
		instance = get_object_or_404(Post, id=id)
		form = PostForm(request.POST or None,  request.FILES or None, instance=instance)
		context = {
			"title": instance.title,
			"instance": instance,
			"form": form,
		}
		return render(request, "post_form.html", context)

	def post(self, request, id=None):
		if not (request.user.is_staff or request.user.is_superuser):
			raise Http404
		instance = get_object_or_404(Post, id=id)
		form = PostForm(request.POST or None,  request.FILES or None, instance=instance)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.save()
			messages.success(request, "Saved")
			return HttpResponseRedirect(instance.get_absolute_url())
		
		
def post_delete(request, id=None):
	if not (request.user.is_staff or request.user.is_superuser):
		raise Http404
	instance = get_object_or_404(Post, id=id)
	instance.delete()
	messages.success(request, "Succesfully deleted")
	return redirect("posts:list")

def adduser(request):
	form = UserForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		new_user = User.objects.create_user(**form.cleaned_data)
		login(request, new_user)
		messages.success(request, "Succesfully created new user")
		return redirect("posts:list")

	context = {
		"form": form,
	}
	return render(request, "post_form.html", context)

blog/templates/base.html
<!--DOCTYPE html -->
{% load staticfiles %}
<html>
<head>
<title> {% block head_title %}Mi blog{% endblock head_title %}</title>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<link rel='stylesheet' href='{% static "css/base.css" %}'/>
<style>
{% block style %}
{% endblock style %}
</style>
</head>
<body>

{% include "messages_display.html" %}

<div class='container'>
{% block content %}

{% endblock content %}
</div>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</body>
</html>

blog/templates/logged_out.html
{% extends 'base.html' %}

{% block title %}See you!{% endblock %}

{% block content %}
  <h2>Logged out</h2>
  <p>You have been successfully logged out.</p>
  <p><a href="{% url 'posts:list' %}">Return to the main page.</a> </p>
{% endblock %}

blog/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" href="{% url "posts:list" %}">Login</button>
  </form>
{% endblock %}

blog/templates/messages_display.html
{% if messages %}
<div class='messages'>
	<ul class="messages">
    	{% for message in messages %}
    	<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    	{% endfor %}
	</ul>
</div>
{% endif %}

blog/templates/post_detail.html
{% extends "base.html" %}

{% block head_title %}{{ instance.title }} | {{ block.super }}{% endblock head_title %}

{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
	<h1>{{title}} </br><small>{{instance.timestamp}}</br></small></h1>
	{% if not instance.user.get_full_name %}
        <p><span class="glyphicon glyphicon-user" aria-hidden="true">Autor: {{ instance.user }}</p>
    {% endif %}
    {% if instance.user.get_full_name %}
        <p><span class="glyphicon glyphicon-user" aria-hidden="true">Autor: {{ instance.user.get_full_name }}</p>
    {% endif %}
	{% if instance.image %}
	<img src='{{ instance.image.url }}' class='img-responsive' />
	<p></p>
	{% endif %}
	<div class="thumbnail">
		<div class="caption">
			<p align="justify">{{ instance.content|linebreaks}}</br></p>
		</div>
	</div>
</div>
<div class='col-sm-4 col-sm-offset-8'>
	<p>Última actualización:{{instance.updated}}</p>

</div>
<div>
	<p></p>
	<a href="{% url "posts:list" %}" class="btn btn-warning" role="button"><span class="glyphicon glyphicon-share-alt" aria-hidden="true">Volver</a>
</div>

<div class='col-sm-8 col-sm-offset-3'>
	<h1>Comentarios:</h1>

	<div class="col-sm-8 ">
	<form method='POST' action=''>{% csrf_token %}
	{{ form.as_p}}
	<input type='submit' value='Comenta' />
	</form>
	</div>
</div>

<div class='col-sm-6 col-sm-offset-3'>
	{% for com in commentary_list %}
	<div class="row">
		<div class="thumbnail">
			<div class="caption">
				<p align="left"><span class="glyphicon glyphicon-user" aria-hidden="true">{{ com.user }} comentó en {{ com.timestamp }}</p>
				<p>{{ com.content }}</p>
			</div>
		</div>
	</div>

	{% endfor %}
</div>
{% endblock content %}

blog/templates/post_form.html
{% extends "base.html" %}

{% block content %}
	<p></p>
	<p></p>
	<div class="col-sm-6 col-sm-offset-3">
	<form method='POST' action='' enctype="multipart/form-data">{% csrf_token %}
	{{ form.as_p}}
	<input type='submit' value='Crear' />
	</form>
	</div>
	<div>
		<p></p>
		<a href="{% url "posts:list" %}" class="btn btn-warning" role="button"><span class="glyphicon glyphicon-share-alt" aria-hidden="true">Volver</a>
	</div>
{% endblock content %}

blog/templates/post_list.html
{% extends "base.html" %}

{% block content %}
  <div class=container-fluid>
  <div class="col-sm-3 col-sm-offset-7">
    <p></p>
    <div class="panel panel-primary">
      <div class="panel-heading">Inicia sesión</div>
      <div class="panel-body">
        <span class="glyphicon glyphicon-off" aria-hidden="true">
        {% if user.is_authenticated %}
          ¡Hola {{ user.username }}!
          <a href="{% url 'logout' %}">logout</a>
        {% else %}
          <a href="{% url 'login' %}">login</a><a href="{% url 'posts:new_user' %}"> registrate</a>
        {% endif %}
      </div>
    </div>



    </div>
    <div class="col-sm-4 col-sm-offset-2">
      <h1>Mi blog</h1>
    </div>
  </div>
  
	<div class="col-sm-8 col-sm-offset-2">
	<form method='GET' action=''>
		<input type='text' name='q' placeholder='Introduzca palabras clave' value='{{ request.GET.q }}'/>
		<input type='submit' value='Buscar'/>
    {% if user.is_staff or request.user.is_superuser %}
      <a href="{% url "posts:create" %}" class="btn btn-success" role="button">Crear</a>
    {% endif %}
	</form>
  </div>


  <div class="col-sm-8 col-sm-offset-2">
	{% for obj in object_list %}
	<div class="row">
		 <div class="col-sm-12">
    		<div class="thumbnail">
      			<div class="caption">
        			<h3>{{obj.title}}<small> {{obj.timestamp|timesince}}</small></h3>
        			{% if not obj.user.get_full_name %}
        				<p><span class="glyphicon glyphicon-user" aria-hidden="true">Autor: {{ obj.user }}</p>
        			{% endif %}
        			{% if obj.user.get_full_name %}
        				<p><span class="glyphicon glyphicon-user" aria-hidden="true">Autor: {{ obj.user.get_full_name }}</p>
        			{% endif %}
       				<p align="justify"> {{obj.content|truncatewords:100|linebreaks}}</p>
        			<a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">Ver</a>
              {% if user.is_staff or request.user.is_superuser %}
        			 <a href="{{ obj.get_absolute_url_edit }}" class="btn btn-success" role="button">Editar</a>
        			 <a href="{{ obj.get_absolute_url_delete }}" class="btn btn-danger" role="button">Eliminar</a>
              {% endif %}
      			</div>
    		</div>
  		</div>
  	</div>
	{% endfor %}


	<div class="pagination">
    	<span class="step-links">
        	{% if object_list.has_previous %}
            	<a href="?page={{ object_list.previous_page_number }}&q={{ request.GET.q }}">previous</a>
        	{% endif %}

        	<span class="current">
            	Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        	</span>

        	{% if object_list.has_next %}
            	<a href="?page={{ object_list.next_page_number }}&q={{ request.GET.q }}">next</a>
        	{% endif %}
    	</span>
	</div>
	</div>
	
{% endblock content %}