elecciones/elecciones/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView

urlpatterns = [
	url(r'^', include("sistema.urls", namespace='sistema')),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'logged_out.html'}, name='logout'),


]

elecciones/sistema/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
	url(r'^$', views.inicio, name='inicio'),
	url(r'^circun_list/$', views.CircunList.as_view(), name='circun_list'),
	url(r'^circun/detail/(?P<pk>\d+)/$', views.CircunDetail.as_view(), name='circun_detail'),
	url(r'^circun/create/$', views.CircunCreate.as_view(), name='circun_create'),
	url(r'^circun/delete/(?P<pk>\d+)/$', views.CircunDelete.as_view(), name='circun_delete'),
	url(r'^circun/update/(?P<pk>\d+)/$', views.CircunUpdate.as_view(), name='circun_update'),
	url(r'^circun/mesas/(?P<id>\d+)/$', views.mesa_list, name='mesa_list'),
	url(r'^circun/mesas/detail/(?P<id>\d+)/$', views.mesa_detail, name='mesa_detail'),
	url(r'^circun/mesas/create/$', views.mesa_create, name='mesa_create'),
	url(r'^circun/mesas/update/(?P<id>\d+)/$', views.mesa_update, name='mesa_update'),
    
]

elecciones/sistema/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

from django.core.urlresolvers import reverse
from django.conf import settings
from django.contrib.auth.models import User

class Partido_politico(models.Model):
	nombre = models.CharField(max_length=120, unique=True)

class Circunscripcion(models.Model):
	nombre = models.CharField(max_length=120)
	num_esca = models.IntegerField()

	def __unicode__(self):
		return self.nombre

	def __str__(self):
		return self.nombre

	def get_absolute_url(self):
		return reverse("sistema:circun_detail", kwargs={"pk": self.pk})

	def get_absolute_url_delete(self):
		return reverse("sistema:circun_delete", kwargs={"pk": self.pk})

	def get_absolute_url_update(self):
		return reverse("sistema:circun_update", kwargs={"pk": self.pk})


class Mesa(models.Model):
	nombre = models.CharField(max_length=120)
	circunscripcion = models.ForeignKey('Circunscripcion')

	def __unicode__(self):
		return self.nombre

	def __str__(self):
		return self.nombre

	def get_absolute_url(self):
		return reverse("sistema:mesa_detail", kwargs={"id": self.id})

	def get_absolute_url_update(self):
		return reverse("sistema:mesa_update", kwargs={"id": self.id})


class Resultado(models.Model):
	votos = models.IntegerField(default=0)
	partido = models.ForeignKey('Partido_politico')
	mesa = models.ForeignKey('Mesa')

elecciones/sistema/forms.py
from django import forms

from .models import Mesa
from django.contrib.auth.models import User


class MesaForm(forms.ModelForm):
	class Meta:
		model = Mesa
		fields = ["nombre", "circunscripcion"]

elecciones/sistema/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect , Http404
from django.contrib import messages

# Create your views here.

from .models import Partido_politico, Circunscripcion, Mesa, Resultado

from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView

from django.core.urlresolvers import reverse_lazy

from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator

from .forms import MesaForm


def inicio(request):
	context = {
		}
	return render(request, "inicio.html", context)

#Test para comprobar supervisor
def is_supervisor(user):
    return user.is_superuser

class CircunList(ListView):
    model = Circunscripcion
    template_name = "sistema/circun_list.html"

class CircunDetail(DetailView):
	model = Circunscripcion
	template_name = "sistema/circun_detail.html"

class CircunCreate(CreateView):
	model = Circunscripcion
	template_name = "sistema/circun_create.html"
	fields = ['nombre','num_esca']

	@method_decorator(user_passes_test(is_supervisor))
	@method_decorator(login_required)
	def dispatch(self, request, *args, **kwargs):
		return super(CircunCreate, self).dispatch(request, *args, **kwargs)

class CircunDelete(DeleteView):
	model = Circunscripcion
	template_name = "sistema/circun_delete.html"
	success_url = reverse_lazy('sistema:circun_list')

	@method_decorator(user_passes_test(is_supervisor))
	@method_decorator(login_required)
	def dispatch(self, request, *args, **kwargs):
		return super(CircunCreate, self).dispatch(request, *args, **kwargs)

class CircunUpdate(UpdateView):
	model = Circunscripcion
	template_name = "sistema/circun_update.html"
	fields = ['nombre','num_esca']

	@method_decorator(user_passes_test(is_supervisor))
	@method_decorator(login_required)
	def dispatch(self, request, *args, **kwargs):
		return super(CircunCreate, self).dispatch(request, *args, **kwargs)


def mesa_list(request, id=None):
	if Circunscripcion.objects.filter(id=id).exists():
		circunscripcion = Circunscripcion.objects.get(id=id)
		mesas = circunscripcion.mesa_set.all()
		context = {
			"circunscripcion_tit": circunscripcion.nombre,
			"mesas": mesas

		}
		return render(request, "mesas_list.html", context)
    
	else:
		return redirect('/notfound')

def mesa_detail(request, id=None):
	instance = get_object_or_404(Mesa, id=id)
	
	
	context = {
		"instance": instance

		}
	return render(request, "mesa_detail.html", context)


def mesa_detail(request, id=None):
	instance = get_object_or_404(Mesa, id=id)
	
	
	context = {
		"instance": instance

		}
	return render(request, "mesa_detail.html", context)

@login_required
@user_passes_test(is_supervisor)
def mesa_create(request):
	if not (request.user.is_superuser):
		raise Http404

	form = MesaForm(request.POST or None)
	if form.is_valid():
			instance = form.save(commit=False)
			instance.save()
			return HttpResponseRedirect(instance.get_absolute_url())
	context = {
		"form": form,
	}
	return render(request, "mesa_form.html", context)

@login_required
@user_passes_test(is_supervisor)
def mesa_update(request, id=None):
	if not (request.user.is_superuser):
		raise Http404

	instance = get_object_or_404(Mesa, id=id)
	form = MesaForm(request.POST or None, instance=instance)
	if form.is_valid():
			instance = form.save(commit=False)
			instance.save()
			return HttpResponseRedirect(instance.get_absolute_url())
	context = {
		"form": form,
	}
	return render(request, "mesa_form.html", context)

elecciones/templates/base.html
<html>
<head>
<title> {% block head_title %}Sistema electoral{% endblock head_title %}</title>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<style>
{% block style %}
{% endblock style %}
</style>
</head>
<body>


<div class='container'>
{% block content %}

{% endblock content %}
</div>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</body>
</html>

elecciones/templates/inicio.html
{% extends "base.html" %}

{% block content %}

<h1>Vista principal</h1>

 <div class=container-fluid>
  <div class="col-sm-3 col-sm-offset-7">
    <p></p>
    <div class="panel panel-primary">
      <div class="panel-heading">Inicia sesión</div>
      <div class="panel-body">
        <span class="glyphicon glyphicon-off" aria-hidden="true">
        {% if user.is_authenticated %}
          ¡Hola {{ user.username }}!
          <a href="{% url 'logout' %}">logout</a>
        {% else %}
          <a href="{% url 'login' %}">login</a>
        {% endif %}
      </div>
    </div>
   </div>
  </div>


<a href="{% url 'sistema:circun_list' %}">Ejercicio 2</a>
{% endblock content %}

elecciones/templates/logged_out.html
{% extends 'base.html' %}

{% block title %}See you!{% endblock %}

{% block content %}
  <h2>Logged out</h2>
  <p>You have been successfully logged out.</p>
  <p><a href="{% url 'sistema:inicio' %}">Return to the main page.</a> </p>
{% endblock %}

elecciones/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" href="{% url "sistema:inicio" %}">Login</button>
  </form>
{% endblock %}

elecciones/templates/mesa_detail.html
{% extends "base.html" %}

{% block content %}
<a href="{% url "sistema:mesa_list" id=instance.circunscripcion.id %}" class="btn btn-warning" role="button"><span class="glyphicon glyphicon-share-alt" aria-hidden="true">Volver</a>

<h3>{{instance.nombre}}</h3>
<p>{{instance.circunscripcion}}</p>

{% endblock content %}

elecciones/templates/mesa_form.html
{% extends "base.html" %}

{% block content %}
	<p></p>
	<p></p>
	<div class="col-sm-6 col-sm-offset-3">
	<form method='POST' action='' >{% csrf_token %}
	{{ form.as_p}}
	<input type='submit' value='Crear' />
	</form>
	</div>
	<div>
		<p></p>
	</div>
{% endblock content %}

elecciones/templates/mesas_list.html
{% extends "base.html" %}

{% block content %}

<a href="{% url "sistema:circun_list" %}" class="btn btn-warning" role="button"><span class="glyphicon glyphicon-share-alt" aria-hidden="true">Volver</a>

<h1>Lista de mesas para {{ circunscripcion_tit }}</h1>
{% if request.user.is_staff or request.user.is_superuser %}
      <a href="{% url "sistema:mesa_create" %}" class="btn btn-success" role="button">Crear</a>
    {% endif %}

<div class="col-sm-8 col-sm-offset-2">
{% for obj in mesas %}
<div class="row">
	<div class="col-sm-12">
    	<div class="thumbnail">
      		<div class="caption">
        			<h3>{{obj.nombre}}</h3>
 					<p>{{obj.circunscripcion}}</p>
 					<a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">Ver</a>
 					<a href="{{ obj.get_absolute_url_update }}" class="btn btn-warning" role="button">Editar</a>
 			</div>
 		</div>
 	</div>
 </div>



{% endfor %}

{% endblock content %}

elecciones/templates/sistema/circun_create.html
{% extends "base.html" %}

{% block content %}
	<p></p>
	<p></p>
	<div class="col-sm-6 col-sm-offset-3">
	<form method='POST' action=''>{% csrf_token %}
	{{ form.as_p}}
	<input type='submit' value='Crear' />
	</form>
	</div>
	<div>
		<p></p>
		<a href="{% url "sistema:circun_list" %}" class="btn btn-warning" role="button"><span class="glyphicon glyphicon-share-alt" aria-hidden="true">Volver</a>
	</div>
{% endblock content %}

elecciones/templates/sistema/circun_delete.html
{% extends "base.html" %}

{% block content %}

<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

{% endblock content %}

elecciones/templates/sistema/circun_detail.html
{% extends "base.html" %}

{% block content %}
<a href="{% url "sistema:circun_list" %}" class="btn btn-warning" role="button"><span class="glyphicon glyphicon-share-alt" aria-hidden="true">Volver</a>

<h3>{{object.nombre}}</h3>
<p>{{object.num_esca}}</p>

{% endblock content %}

elecciones/templates/sistema/circun_list.html
{% extends "base.html" %}

{% block content %}

<h1>Lista de circunscripciones</h1>

<div class="col-sm-8 col-sm-offset-2">
{% if request.user.is_staff or request.user.is_superuser %}
      <a href="{% url "sistema:circun_create" %}" class="btn btn-success" role="button">Crear</a>
    {% endif %}
{% for obj in object_list %}
<div class="row">
	<div class="col-sm-12">
    	<div class="thumbnail">
      		<div class="caption">
        			<h3>{{obj.nombre}}</h3> <a href="{% url 'sistema:mesa_list' id=obj.pk %}">Ver mesas</a>
 					<p>{{obj.num_esca}}</p>
 					<a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">Ver</a>
 					<a href="{{ obj.get_absolute_url_delete }}" class="btn btn-danger" role="button">Eliminar</a>
 					<a href="{{ obj.get_absolute_url_update }}" class="btn btn-warning" role="button">Editar</a>
 			</div>
 		</div>
 	</div>
 </div>



{% endfor %}

{% endblock content %}

elecciones/templates/sistema/circun_update.html
{% extends "base.html" %}

{% block content %}
	<p></p>
	<p></p>
	<div class="col-sm-6 col-sm-offset-3">
	<form method='POST' action=''>{% csrf_token %}
	{{ form.as_p}}
	<input type='submit' value='Crear' />
	</form>
	</div>
	<div>
		<p></p>
		<a href="{% url "sistema:circun_list" %}" class="btn btn-warning" role="button"><span class="glyphicon glyphicon-share-alt" aria-hidden="true">Volver</a>
	</div>
{% endblock content %}